/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { AnotherServiceClientContext } from "./anotherServiceClientContext";


class AnotherServiceClient extends AnotherServiceClientContext {
  // Operation groups
  test: operations.Test;

  /**
   * Initializes a new instance of the AnotherServiceClient class.
   * @param credentials Credentials needed for the client to connect to Azure.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.AnotherServiceClientOptions) {
    super(credentials, options);
    this.test = new operations.Test(this);
  }
}

// Operation Specifications

export {
  AnotherServiceClient,
  AnotherServiceClientContext,
  Models as AnotherServiceModels,
  Mappers as AnotherServiceMappers
};
export * from "./operations";
